import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
        ]),
      ),
    );
  }
}

class HomeInitialScreen extends StatelessWidget {
const HomeInitialScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.black),
          child: Stack(
            children: [
              Positioned(
                left: 182,
                top: 750,
                child: SizedBox(
                  width: 89,
                  height: 32,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 28,
                        top: 20,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(2.43),
                          child: Container(
                            width: 18.44,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                  color: Color(0xFFFD473B),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 11,
                        child: Container(
                          width: 89,
                          height: 10,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFD473B),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 2,
                        top: 0,
                        child: SizedBox(
                          width: 87,
                          height: 20,
                          child: Text(
                            'タップで検索',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Noto Sans JP',
                              fontWeight: FontWeight.w700,
                              decoration: TextDecoration.none,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 768,
                child: Opacity(
                  opacity: 0.10,
                  child: Container(
                    width: 393,
                    height: 84,
                    decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 782,
                child: SizedBox(
                  width: 336,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 265,
                        top: 0,
                        child: SizedBox(
                          width: 71,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 28,
                                child: SizedBox(
                                  width: 71,
                                  height: 16,
                                  child: Text(
                                    'マイリスト',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF777777),
                                      fontSize: 13,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w500,
                                      decoration: TextDecoration.none,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24,
                                top: 0,
                                child: Icon(
                                  Icons.favorite,
                                  size: 21,
                                  color: Color(0xFF777777),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 137,
                        top: 0,
                        child: SizedBox(
                          width: 48,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 28,
                                child: SizedBox(
                                  width: 48,
                                  height: 16,
                                  child: Text(
                                    '検索',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF777777),
                                      fontSize: 13,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w500,
                                      decoration: TextDecoration.none,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 13.5,
                                top: 2,
                                child: Icon(
                                  Icons.search,
                                  size: 21,
                                  color: Color(0xFF777777),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 48,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 28,
                                child: SizedBox(
                                  width: 48,
                                  height: 16,
                                  child: Text(
                                    'ホーム',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w500,
                                      decoration: TextDecoration.none,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 13.5,
                                top: 2,
                                child: Icon(
                                  Icons.home,
                                  size: 21,
                                  color: Colors.white,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 604,
                child: SizedBox(
                  width: 360,
                  height: 110,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Opacity(
                          opacity: 0.60,
                          child: Container(
                            width: 360,
                            height: 110,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(color: Colors.white),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 26.76,
                        child: SizedBox(
                          width: 307,
                          height: 57.48,
                          child: Text(
                            '広告エリア',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                              decoration: TextDecoration.none,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 8,
                top: 316,
                child: SizedBox(
                  width: 377,
                  height: 120,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 64,
                        child: SizedBox(
                          width: 377,
                          height: 56,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 337,
                                top: 19,
                                child: Container(
                                  width: 20,
                                  height: 18,
                                  padding: const EdgeInsets.only(right: 0.31, bottom: 0.10),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 19.69,
                                        height: 17.90,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: SizedBox(
                                                width: 20,
                                                height: 18,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Container(
                                                      width: 20,
                                                      height: 18,
                                                      decoration: BoxDecoration(color: Color(0xFFD8D8D8)),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 126,
                                top: 31,
                                child: SizedBox(
                                  width: 168,
                                  height: 16,
                                  child: Opacity(
                                    opacity: 0.50,
                                    child: Text(
                                      '和歌山県すさみ町見老津',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 13,
                                        fontFamily: 'Noto Sans JP',
                                        fontWeight: FontWeight.w500,
                                        decoration: TextDecoration.none,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 36,
                                child: SizedBox(
                                  width: 7,
                                  height: 9,
                                  child: Icon(
                                    Icons.location_pin,
                                    size: 9,
                                    color: Color(0xFF777777),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 9,
                                child: SizedBox(
                                  width: 115,
                                  height: 20,
                                  child: Text(
                                    '林渡船',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 18,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w900,
                                      decoration: TextDecoration.none,
                                    ),
                                  ),
                                ),
                              ), 
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 95,
                                  height: 56,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: AssetImage("assets/images/placeholder_image.png"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 377,
                          height: 56,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 337,
                                top: 19,
                                child: Container(
                                  width: 20,
                                  height: 18,
                                  padding: const EdgeInsets.only(right: 0.31, bottom: 0.10),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 19.69,
                                        height: 17.90,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: SizedBox(
                                                width: 20,
                                                height: 18,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Container(
                                                      width: 20,
                                                      height: 18,
                                                      decoration: BoxDecoration(color: Color(0xFFD8D8D8)),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 126,
                                top: 31,
                                child: SizedBox(
                                  width: 168,
                                  height: 16,
                                  child: Opacity(
                                    opacity: 0.50,
                                    child: Text(
                                      '和歌山県すさみ町見老津',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 13,
                                        fontFamily: 'Noto Sans JP',
                                        fontWeight: FontWeight.w500,
                                        decoration: TextDecoration.none,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 36,
                                child: SizedBox(
                                  width: 7,
                                  height: 9,
                                  child: Icon(
                                    Icons.location_pin,
                                    size: 9,
                                    color: Color(0xFF777777),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 207,
                                top: 15,
                                child: Container(
                                  width: 8,
                                  height: 8,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF8DCDD6),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 9,
                                child: SizedBox(
                                  width: 115,
                                  height: 20,
                                  child: Text(
                                    '浜丸渡船',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 18,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w900,
                                      decoration: TextDecoration.none,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 95,
                                  height: 56,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: AssetImage("assets/images/placeholder_image.png"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 6,
                top: 273,
                child: SizedBox(
                  width: 401,
                  height: 28,
                  child: Text(
                    '現在は未登録です',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Noto Sans JP',
                      fontWeight: FontWeight.w700,
                      decoration: TextDecoration.none,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 8,
                top: 245,
                child: SizedBox(
                  width: 401,
                  height: 28,
                  child: Text(
                    '🔍をタップして自分だけのリストを作成しよう',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Noto Sans JP',
                      fontWeight: FontWeight.w700,
                      decoration: TextDecoration.none,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 8,
                top: 204,
                child: SizedBox(
                  width: 255,
                  height: 40,
                  child: Text(
                    'マイリスト',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 27,
                      fontFamily: 'Noto Sans JP',
                      fontWeight: FontWeight.w700,
                      decoration: TextDecoration.none,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 73,
                child: SizedBox(
                  width: 360,
                  height: 111,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Opacity(
                          opacity: 0.60,
                          child: Container(
                            width: 360,
                            height: 111,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(color: Colors.white),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 27,
                        child: SizedBox(
                          width: 307,
                          height: 58,
                          child: Text(
                            '広告エリア',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                              decoration: TextDecoration.none,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 191,
                top: -38,
                child: Container(
                  width: 100,
                  height: 100,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}


