import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
        ]),
      ),
    );
  }
}

class  extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.black),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 768,
                child: Opacity(
                  opacity: 0.10,
                  child: Container(
                    width: 393,
                    height: 84,
                    decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 782,
                child: SizedBox(
                  width: 336,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 265,
                        top: 0,
                        child: SizedBox(
                          width: 71,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 28,
                                child: SizedBox(
                                  width: 71,
                                  height: 16,
                                  child: Text(
                                    'マイリスト',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 13,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24,
                                top: 0,
                                child: Container(
                                  width: 23,
                                  height: 21,
                                  padding: const EdgeInsets.only(right: 0.35, bottom: 0.12),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 22.65,
                                        height: 20.88,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: SizedBox(
                                                width: 23,
                                                height: 21,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  children: [
                                                    Container(
                                                      width: 23,
                                                      height: 21,
                                                      decoration: BoxDecoration(color: Colors.white),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 137,
                        top: 0,
                        child: SizedBox(
                          width: 48,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 28,
                                child: SizedBox(
                                  width: 48,
                                  height: 16,
                                  child: Text(
                                    '検索',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF777777),
                                      fontSize: 13,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 48,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 28,
                                child: SizedBox(
                                  width: 48,
                                  height: 16,
                                  child: Text(
                                    'ホーム',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF777777),
                                      fontSize: 13,
                                      fontFamily: 'Noto Sans JP',
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 621,
                child: SizedBox(
                  width: 360,
                  height: 110,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Opacity(
                          opacity: 0.60,
                          child: Container(
                            width: 360,
                            height: 110,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(color: Colors.white),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 26.76,
                        child: SizedBox(
                          width: 307,
                          height: 57.48,
                          child: Text(
                            '広告エリア',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                              letterSpacing: 0.50,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 50,
                top: 178,
                child: SizedBox(
                  width: 335,
                  height: 56,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 126,
                        top: 31,
                        child: SizedBox(
                          width: 168,
                          height: 16,
                          child: Opacity(
                            opacity: 0.50,
                            child: Text(
                              '和歌山県すさみ町見老津',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 13,
                                fontFamily: 'Noto Sans JP',
                                fontWeight: FontWeight.w500,
                                letterSpacing: 0.90,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 115,
                        top: 36,
                        child: SizedBox(width: 7, height: 9, child: Stack()),
                      ),
                      Positioned(
                        left: 115,
                        top: 9,
                        child: SizedBox(
                          width: 115,
                          height: 20,
                          child: Text(
                            '浜丸渡船',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontFamily: 'Noto Sans JP',
                              fontWeight: FontWeight.w900,
                              letterSpacing: 0.90,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 191,
                child: SizedBox(width: 13, height: 30, child: Stack()),
              ),
              Positioned(
                left: 14,
                top: 124,
                child: SizedBox(
                  width: 320,
                  height: 40,
                  child: Text(
                    '並べ替え',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Noto Sans JP',
                      fontWeight: FontWeight.w700,
                      letterSpacing: 0.90,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Opacity(
                  opacity: 0.30,
                  child: Container(
                    width: 393,
                    height: 111,
                    decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 54,
                child: SizedBox(
                  width: 192,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 24,
                        top: 0,
                        child: SizedBox(
                          width: 168,
                          height: 40,
                          child: Text(
                            'マイリスト',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 27,
                              fontFamily: 'Noto Sans JP',
                              fontWeight: FontWeight.w700,
                              letterSpacing: 0.90,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 10,
                        child: Container(
                          width: 12,
                          height: 20,
                          padding: const EdgeInsets.only(right: 0.03, bottom: 0.89),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 11.97,
                                height: 19.11,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: SizedBox(
                                        width: 12,
                                        height: 20,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            Container(
                                              width: 12,
                                              height: 20,
                                              decoration: BoxDecoration(color: Colors.white),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}